### ISSUE TITLE
$ in equitation

### ISSUE THREAD

**Issue by TrejGun** [mikolalysenko/mathmode#3]
So i have to pass $ to equitation

``` js
sanitize("X = $5 ")
```

which is equivalent to

``` js
"X = $5".replace(/\$/g, "")
```

but i would never see `$` again even after escape it

``` js
"X = $5".replace(/\$/g, "\$").replace(/\$/g, "") // "X = 5"
"X = $5".replace(/\$/g, "\\$").replace(/\$/g, "") // "X = \5"
```

**Comment by mikolalysenko** [comment]
Ok, the latest patch should fix this.  Try using `\$` to write a dollar sign in an equation.

**Comment by TrejGun** [comment]
``` js
"\\\\\\$ \\$ $".replace(/([^\\](\\\\)*)(\$)/g, "$1") // "\\\$ \$ "
```

so i will loose my $ sign
unfortunately i can't use negative look behind but can use function

``` js
"\\\\\\$ \\$ $".replace(/(\\)?\$/g, function ($0, $1) { return $1?$0:"\\"+$0; }) // "\\\$ \$ \$"
```

in this case i will have my last $ sign escaped

**Comment by mikolalysenko** [comment]
Well, in regular latex an unescaped $ is an invalid character, and so I don't see much harm in just removing them.  (Maybe reporting an error would be better?)

Also your second example fails to escape the $ in the string:

``` javascript
"\\\\$"
```

**Comment by TrejGun** [comment]
it doesn't) it adds `\\` only if it absent

**Comment by mikolalysenko** [comment]
Your function maps `"\\\\$"` to `"\\\\$"`, which escapes in latex to `\\$`.  This is an unescaped $ token and will cause an error.
